### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by HardyRD** [davelpz/clock#1]
When executing the game on my Galaxy S5, I receive a run time error and the application closes.  
![runtime error 20151202](https://cloud.githubusercontent.com/assets/15602781/11539480/41b97e84-98f5-11e5-8df1-87325650418b.jpg)

**Comment by HardyRD** [comment]
I have not had this happen in the tablet yet.

**Comment by davelpz** [comment]
fixed, should not happen in next build

**Comment by davelpz** [comment]
fixed in build 19
