### ISSUE TITLE
Add basic sound effects

### ISSUE THREAD

**Issue by davelpz** [davelpz/clock#13]
Need some sounds when moving cards around and placing them

**Comment by HardyRD** [comment]
Keep in mind that sounds should be able to be muted in the settings.

**Comment by davelpz** [comment]
yes, bear, I think that is covered in issue #7

**Comment by HardyRD** [comment]
When a King is selected,  make an ominous sound vs the same sound as the other cards.

**Comment by davelpz** [comment]
basic sounds added
not the best, need to find better ones
